### ISSUE TITLE
Incorrect token

### ISSUE THREAD

**Issue by uros76** [Woodie-07/EarnApp.py#11]
Hi. I have been using this script successfully for more than half a year but last few days it seems the google authentication token is not accepted anymore. 

What I did to try and fix: 
I have logged in to earnapp dashboard and collected the token from the cookie. I noticed the token is now much longer. Then I used it in the script the same as before. Still, I get the "Incorrect token" error. 

Any idea what could be wrong? Did google change something?

**Comment by Woodie-07** [comment]
Hmm... it seems EarnApp have removed the oauth-refresh-token, so we have to use the oauth-token now. I'll push a fix ASAP.
![Screenshot 2022-12-04 at 11 02 17](https://user-images.githubusercontent.com/40068306/205486969-40098f00-0b27-4fa4-86c2-9444d38dc47e.png)

**Comment by Woodie-07** [comment]
I have published version 0.1.7, try now.

**Comment by uros76** [comment]
Thanks for the quick response. I upgraded to the 0.1.7 version but still get Incorrect token output when I try to pull the balance.

**Comment by Woodie-07** [comment]
Are you sure you're entering the oauth-token from the dashboard? It seemed to work fine in my testing before I pushed the fix.

**Comment by uros76** [comment]
Yes. I am using oath-token from earnapp dashboard
![image](https://user-images.githubusercontent.com/25409772/205581530-c5595d4b-a1d6-4230-942c-3e28daa4a962.png)

**Comment by Woodie-07** [comment]
They have added oauth-refresh-token back, I have updated the library to work with this change. Please try oauth-refresh-token again.

**Comment by uros76** [comment]
Excellent work. Thanks a lot. With 0.1.8 version and oauth-refresh-token it is working again

**Comment by uros76** [comment]
Hi @Woodie-07. It seems earnapp changed something again 😒 again I am getting incorrect token errors. 
This is the current screenshot of the dashboard cookie section. I tried both oath-token and oath-refresh-token and it doesn't work...
![image](https://user-images.githubusercontent.com/25409772/210215824-da7390ba-ccde-439e-9084-b9e8216be23e.png)

**Comment by Woodie-07** [comment]
Forgot to reply to this, should be fixed in the latest version.
